import QuantitySelector from "./QuantitySelector";
import type { StoreProduct } from "../../types/ecommerce";

type ProductInfoProps = { product: StoreProduct; quantity: number; isWishlisted: boolean; onQuantityChange: (quantity: number) => void; onAddToCart: () => void; onToggleWishlist: () => void };
const formatPrice = (price: number) => `\u20B9${price.toLocaleString("en-IN")}`;

export default function ProductInfo({ product, quantity, isWishlisted, onQuantityChange, onAddToCart, onToggleWishlist }: ProductInfoProps) {
  const inStock = product.stock > 0; const rating = product.rating ?? 4.8;
  return <div className="p-6 sm:p-8 lg:p-10"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-cyan-400/10 px-3 py-1.5 text-sm font-semibold text-cyan-300">{product.category}</span><span className="rounded-full bg-yellow-400/10 px-3 py-1.5 text-sm font-semibold text-yellow-200"><span aria-hidden="true">&#9733;</span> {rating.toFixed(1)}</span></div><h1 className="mt-5 text-3xl font-extrabold tracking-tight text-white sm:text-4xl lg:text-5xl">{product.name}</h1><p className="mt-6 text-base leading-8 text-gray-400">{product.description}</p><p className="mt-8 text-4xl font-extrabold tracking-tight text-purple-400">{formatPrice(product.price)}</p><div className={`mt-6 rounded-2xl border p-4 ${inStock ? "border-emerald-400/20 bg-emerald-400/5" : "border-red-400/20 bg-red-400/5"}`}><p className={`font-semibold ${inStock ? "text-emerald-300" : "text-red-300"}`}>{inStock ? "In stock" : "Out of stock"}</p><p className="mt-1 text-sm text-gray-400">{inStock ? `${product.stock} unit${product.stock === 1 ? "" : "s"} available` : "This product is currently unavailable."}</p></div><div className="mt-8 flex flex-wrap items-center gap-4"><QuantitySelector value={quantity} max={product.stock} onChange={onQuantityChange} disabled={!inStock} /><button type="button" onClick={onAddToCart} disabled={!inStock} className="min-h-12 flex-1 rounded-xl bg-gradient-to-r from-purple-600 to-cyan-500 px-6 py-3 font-bold text-white shadow-lg shadow-purple-950/30 transition duration-200 hover:-translate-y-0.5 hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50">Add to Cart</button><button type="button" onClick={onToggleWishlist} className={`min-h-12 rounded-xl border px-5 py-3 font-semibold transition ${isWishlisted ? "border-pink-500 bg-pink-500 text-white" : "border-cyan-400/60 text-cyan-300 hover:bg-cyan-400 hover:text-[#0A0A0F]"}`} aria-pressed={isWishlisted}>{isWishlisted ? "Saved" : "Wishlist"} <span aria-hidden="true">&#9825;</span></button></div></div>;
}
