import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import axios from "axios";
import { useNavigate, useSearchParams } from "react-router-dom";
import api from "../services/api";

type ProductForm = { name: string; description: string; price: string; stock: string; category: string; };
const emptyForm: ProductForm = { name: "", description: "", price: "", stock: "", category: "" };
const errorMessage = (error: unknown) => axios.isAxiosError(error) && typeof error.response?.data?.error === "string" ? error.response.data.error : "Operation failed. Please try again.";

export default function AdminDashboard() {
  const [searchParams] = useSearchParams(); const navigate = useNavigate(); const productId = searchParams.get("id");
  const [form, setForm] = useState<ProductForm>(emptyForm); const [loading, setLoading] = useState(false); const [fetching, setFetching] = useState(Boolean(productId)); const [success, setSuccess] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (!productId) return; const fetchProduct = async () => { try { const { data } = await api.get<ProductForm>(`/products/${productId}`); setForm({ name: data.name, description: data.description, price: String(data.price), stock: String(data.stock), category: data.category }); } catch (requestError: unknown) { setError(errorMessage(requestError)); } finally { setFetching(false); } }; void fetchProduct(); }, [productId]);
  const handleChange = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); setSuccess(""); const payload = { ...form, price: Number(form.price), stock: Number(form.stock) }; try { if (productId) await api.put(`/products/${productId}`, payload); else await api.post("/products", { ...payload, embedding: [0] }); setSuccess(productId ? "Product updated successfully." : "Product added successfully."); window.setTimeout(() => navigate("/"), 1000); } catch (requestError: unknown) { setError(errorMessage(requestError)); } finally { setLoading(false); } };
  const inputClassName = "mt-2 w-full rounded-xl border border-gray-700 bg-[#0A0A0F] px-4 py-3 text-white placeholder:text-gray-500 focus:border-cyan-400 focus:outline-none focus:ring-2 focus:ring-cyan-400/20 disabled:opacity-60";
  return <section className="min-h-screen bg-[#0A0A0F] px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-3xl"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-400">Catalog management</p><h1 className="mt-2 text-3xl font-bold text-purple-400 sm:text-4xl">{productId ? "Edit Product" : "Add Product"}</h1><p className="mt-2 text-gray-400">{productId ? "Update the product details below." : "Create a new product for the ShopSphere catalog."}</p></div><div className="rounded-2xl border border-gray-800 bg-[#111118] p-5 shadow-2xl shadow-black/20 sm:p-8">{fetching ? <div className="flex min-h-80 items-center justify-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-purple-500 border-t-cyan-400" aria-label="Loading product" /></div> : <><>{error && <div role="alert" className="mb-6 rounded-xl border border-red-500/60 bg-red-500/10 p-4 text-red-200">{error}</div>}{success && <div role="status" className="mb-6 rounded-xl border border-emerald-400/60 bg-emerald-400/10 p-4 text-emerald-200">{success}</div>}</><form onSubmit={handleSubmit} className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium text-gray-300">Product Name<input name="name" value={form.name} onChange={handleChange} required disabled={loading} className={inputClassName} placeholder="Product name" /></label><label className="text-sm font-medium text-gray-300">Category<input name="category" value={form.category} onChange={handleChange} required disabled={loading} className={inputClassName} placeholder="e.g. Electronics" /></label><label className="text-sm font-medium text-gray-300 md:col-span-2">Description<textarea name="description" value={form.description} onChange={handleChange} required disabled={loading} className={`${inputClassName} min-h-32 resize-y`} placeholder="Describe the product" /></label><label className="text-sm font-medium text-gray-300">Price<input name="price" type="number" min="0" step="0.01" value={form.price} onChange={handleChange} required disabled={loading} className={inputClassName} placeholder="0.00" /></label><label className="text-sm font-medium text-gray-300">Stock<input name="stock" type="number" min="0" step="1" value={form.stock} onChange={handleChange} required disabled={loading} className={inputClassName} placeholder="0" /></label><button type="submit" disabled={loading} className="md:col-span-2 mt-2 flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-purple-600 to-cyan-500 px-5 py-3 font-semibold transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />}{loading ? "Saving..." : productId ? "Update Product" : "Add Product"}</button></form></>}</div></div></section>;
}
