import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import EmptyState from "../components/commerce/EmptyState";
import api from "../services/api";
import type { ApiOrder, OrderStatus } from "../types/ecommerce";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";

const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
const badge: Record<OrderStatus, string> = { Pending: "bg-yellow-400/10 text-yellow-200", Confirmed: "bg-blue-400/10 text-blue-300", Packed: "bg-orange-400/10 text-orange-300", Shipped: "bg-purple-400/10 text-purple-300", Delivered: "bg-emerald-400/10 text-emerald-300", Cancelled: "bg-red-400/10 text-red-300" };

export default function OrdersPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { notify } = useToast();
  const [orders, setOrders] = useState<ApiOrder[]>([]); const [selected, setSelected] = useState<ApiOrder | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { if (id) { const response = await api.get<{ order: ApiOrder }>(`/orders/${id}`); setSelected(response.data.order); } else { const response = await api.get<{ orders: ApiOrder[] }>("/orders"); setOrders(response.data.orders); } } catch { setError("Unable to load orders. Please sign in and try again."); } finally { setLoading(false); } };
  useEffect(() => { if (user) void load(); else setLoading(false); }, [id, user]);
  const cancel = async (order: ApiOrder) => { if (!window.confirm("Cancel this pending order?")) return; try { await api.delete(`/orders/${order.id}`); notify("Order cancelled successfully."); await load(); } catch { notify("Only pending orders can be cancelled.", "error"); } };
  if (!user) return <main className="mx-auto min-h-screen max-w-4xl px-4 py-16"><EmptyState title="Sign in to view your orders" text="Your order history is securely linked to your account." action="Sign in" to="/login" /></main>;
  if (loading) return <main className="mx-auto min-h-screen max-w-5xl px-4 py-12"><div className="h-8 w-48 animate-pulse rounded bg-white/10" /><div className="mt-8 space-y-4">{[1, 2, 3].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-white/5" />)}</div></main>;
  if (error) return <main className="mx-auto min-h-screen max-w-5xl px-4 py-16 text-center text-red-200">{error}</main>;
  if (id && selected) return <OrderDetails order={selected} onBack={() => navigate("/orders")} onCancel={() => void cancel(selected)} />;
  if (!orders.length) return <main className="mx-auto min-h-screen max-w-5xl px-4 py-12"><EmptyState title="No orders yet" text="When you place an order, the details will appear here." action="Start shopping" to="/catalog" /></main>;
  return <main className="mx-auto min-h-screen max-w-5xl px-4 py-12 text-white sm:px-6"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-cyan-400">Account</p><h1 className="mt-2 text-3xl font-bold">Order History</h1><div className="mt-8 space-y-4">{orders.map((order) => <article key={order.id} className="rounded-2xl border border-gray-800 bg-[#111118] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold">{order.orderNumber}</p><p className="mt-1 text-sm text-gray-400">{new Date(order.createdAt).toLocaleDateString("en-IN", { dateStyle: "medium" })}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${badge[order.status]}`}>{order.status}</span><p className="mt-3 font-bold text-purple-400">{money(order.totalAmount)}</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-gray-800 pt-4"><p className="text-sm text-gray-400">{order.items.map((item) => `${item.name} × ${item.quantity}`).join(", ")}</p><div className="flex gap-3"><Link to={`/orders/${order.id}`} className="text-sm font-semibold text-cyan-300 hover:text-cyan-200">View details</Link>{order.status === "Pending" && <button type="button" onClick={() => void cancel(order)} className="text-sm font-semibold text-red-300 hover:text-red-200">Cancel</button>}</div></div></article>)}</div></main>;
}

function OrderDetails({ order, onBack, onCancel }: { order: ApiOrder; onBack: () => void; onCancel: () => void }) { return <main className="mx-auto min-h-screen max-w-4xl px-4 py-12 text-white sm:px-6"><button type="button" onClick={onBack} className="text-sm font-semibold text-cyan-300">← Back to orders</button><div className="mt-5 rounded-2xl border border-gray-800 bg-[#111118] p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-gray-400">Order details</p><h1 className="mt-1 text-2xl font-bold">{order.orderNumber}</h1><p className="mt-2 text-sm text-gray-400">{new Date(order.createdAt).toLocaleString("en-IN")}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${badge[order.status]}`}>{order.status}</span><p className="mt-3 text-2xl font-bold text-purple-400">{money(order.totalAmount)}</p></div></div><div className="mt-8 grid gap-6 border-t border-gray-800 pt-6 sm:grid-cols-2"><div><h2 className="font-semibold">Products</h2><div className="mt-3 space-y-3">{order.items.map((item) => <div key={`${item.product}-${item.name}`} className="flex justify-between gap-4 text-sm text-gray-300"><span>{item.name} × {item.quantity}</span><span>{money(item.price * item.quantity)}</span></div>)}</div></div><div className="space-y-5 text-sm"><div><h2 className="font-semibold">Shipping address</h2><p className="mt-2 text-gray-400">{order.shippingAddress}</p></div><div><h2 className="font-semibold">Payment method</h2><p className="mt-2 text-gray-400">{order.paymentMethod}</p></div></div></div>{order.status === "Pending" && <button type="button" onClick={onCancel} className="mt-8 rounded-xl border border-red-400/30 px-4 py-2.5 text-sm font-semibold text-red-300 hover:bg-red-400/10">Cancel order</button>}</div></main>; }
