import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import api from "../services/api";

type Product = { id: string; name: string; description: string; price: number; stock: number; category: string; imageUrl?: string; };

export default function ProductDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState<Product | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [deleting, setDeleting] = useState(false);
  useEffect(() => { const fetchProduct = async () => { try { const { data } = await api.get<Product>(`/products/${id}`); setProduct(data); } catch { setError("Product not found or unavailable."); } finally { setLoading(false); } }; void fetchProduct(); }, [id]);
  const handleDelete = async () => { if (!id || !window.confirm("Are you sure you want to delete this product?")) return; setDeleting(true); try { await api.delete(`/products/${id}`); navigate("/"); } catch { setError("Failed to delete product."); setDeleting(false); } };
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#0A0A0F]"><div className="h-10 w-10 animate-spin rounded-full border-4 border-purple-500 border-t-cyan-400" aria-label="Loading product" /></div>;
  if (!product) return <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-[#0A0A0F] px-4 text-center text-white"><h1 className="text-3xl font-bold">Product Not Found</h1><p className="text-gray-400">{error || "This product is no longer available."}</p><Link to="/" className="rounded-xl border border-cyan-400 px-5 py-3 font-semibold text-cyan-300">Back to catalog</Link></div>;
  const isInStock = product.stock > 0;
  return <section className="min-h-screen bg-[#0A0A0F] px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-6xl"><Link to="/" className="inline-flex rounded-lg px-3 py-2 text-sm font-semibold text-cyan-300 transition hover:bg-white/5">← Back to catalog</Link>{error && <div role="alert" className="mt-5 rounded-xl border border-red-500/60 bg-red-500/10 p-4 text-red-200">{error}</div>}<div className="mt-5 overflow-hidden rounded-3xl border border-gray-800 bg-[#111118] shadow-2xl shadow-black/30 lg:grid lg:grid-cols-2"><div className="relative min-h-80 overflow-hidden bg-[#171722]"><img src={product.imageUrl ?? "https://placehold.co/1000x1000/1F2937/FFFFFF?text=Product"} alt={product.name} className="h-full min-h-80 w-full object-cover transition duration-500 hover:scale-105" /><span className="absolute left-5 top-5 rounded-full bg-cyan-400 px-3 py-1.5 text-sm font-bold text-[#0A0A0F]">{product.category}</span><span className="absolute right-5 top-5 rounded-full bg-yellow-300 px-3 py-1.5 text-sm font-bold text-[#16120a]">★ 4.8</span></div><div className="p-6 sm:p-10"><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-sm font-semibold ${isInStock ? "bg-emerald-400/10 text-emerald-300" : "bg-red-400/10 text-red-300"}`}>{isInStock ? "In stock" : "Out of stock"}</span><span className="text-sm text-gray-400">Premium quality selection</span></div><h1 className="mt-5 text-3xl font-extrabold tracking-tight sm:text-5xl">{product.name}</h1><p className="mt-6 leading-8 text-gray-400">{product.description}</p><p className="mt-8 text-4xl font-bold text-purple-400 sm:text-5xl">₹{product.price.toLocaleString("en-IN")}</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-gray-800 bg-[#0A0A0F] p-5"><p className="text-sm text-gray-500">Availability</p><p className={`mt-2 text-xl font-bold ${isInStock ? "text-emerald-300" : "text-red-300"}`}>{isInStock ? `${product.stock} units ready` : "Currently unavailable"}</p></div><div className="rounded-2xl border border-gray-800 bg-[#0A0A0F] p-5"><p className="text-sm text-gray-500">Delivery</p><p className="mt-2 text-xl font-bold text-cyan-300">Free shipping</p></div></div><div className="mt-8 flex flex-wrap gap-3"><Link to={`/admin?id=${product.id}`} className="rounded-xl bg-gradient-to-r from-purple-600 to-cyan-500 px-5 py-3 font-semibold transition hover:brightness-110">Edit Product</Link><button type="button" onClick={handleDelete} disabled={deleting} className="rounded-xl border border-red-500/70 px-5 py-3 font-semibold text-red-300 transition hover:bg-red-500 hover:text-white disabled:cursor-not-allowed disabled:opacity-60">{deleting ? "Deleting..." : "Delete"}</button></div></div></div></div></section>;
}
