import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import AuthLayout, { authInputClass, googleButtonClass, primaryButtonClass } from "../components/auth/AuthLayout";
import { useAuth } from "../hooks/useAuth";

type FormErrors = { name?: string; email?: string; password?: string; confirmPassword?: string };

export default function SignupPage() {
  const navigate = useNavigate(); const { signup } = useAuth(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [errors, setErrors] = useState<FormErrors>({}); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(false);
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const nextErrors: FormErrors = {}; if (!name.trim()) nextErrors.name = "Full name is required."; if (!email.trim()) nextErrors.email = "Email is required."; if (!password) nextErrors.password = "Password is required."; else if (password.length < 6) nextErrors.password = "Password must be at least 6 characters."; if (!confirmPassword) nextErrors.confirmPassword = "Please confirm your password."; else if (password !== confirmPassword) nextErrors.confirmPassword = "Passwords do not match."; setErrors(nextErrors); setError(""); setSuccess(""); if (Object.keys(nextErrors).length) return; setLoading(true); try { await signup(name.trim(), email.trim(), password); setSuccess("Account created successfully. Redirecting to login..."); window.setTimeout(() => navigate("/login"), 1000); } catch (requestError: unknown) { setError(requestError instanceof Error ? requestError.message : "Registration failed."); } finally { setLoading(false); } };
  const fieldError = (message: string | undefined) => message && <span className="mt-1.5 block text-sm text-red-400">{message}</span>;

  return <AuthLayout eyebrow="Join ShopSphere" title="Create your account" subtitle="Make every shopping moment feel a little more considered.">
    {error && <div role="alert" className="mt-7 rounded-xl border border-red-500/70 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}{success && <div role="status" className="mt-7 rounded-xl border border-cyan-400/70 bg-cyan-400/10 px-4 py-3 text-sm text-cyan-200">{success}</div>}
    <form onSubmit={handleSubmit} noValidate className="mt-8 space-y-4"><label className="block text-sm font-semibold text-gray-300">Full Name<input type="text" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} disabled={loading} className={authInputClass} placeholder="Your full name" />{fieldError(errors.name)}</label><label className="block text-sm font-semibold text-gray-300">Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} disabled={loading} className={authInputClass} placeholder="you@example.com" />{fieldError(errors.email)}</label><label className="block text-sm font-semibold text-gray-300">Password<input type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={loading} className={authInputClass} placeholder="At least 6 characters" />{fieldError(errors.password)}</label><label className="block text-sm font-semibold text-gray-300">Confirm Password<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} disabled={loading} className={authInputClass} placeholder="Re-enter your password" />{fieldError(errors.confirmPassword)}</label><button type="submit" disabled={loading} className={`mt-2 ${primaryButtonClass}`}>{loading ? "Creating account..." : "Create Account"}</button></form>
    <div className="my-7 flex items-center gap-4 text-xs font-semibold uppercase tracking-[0.18em] text-gray-500"><span className="h-px flex-1 bg-gray-800" />or<span className="h-px flex-1 bg-gray-800" /></div><button type="button" onClick={() => setError("Google sign-in is not configured yet.")} className={googleButtonClass}><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-xs font-bold text-[#4285F4]">G</span>Continue with Google</button>
    <p className="mt-8 text-center text-sm text-gray-400">Already have an account? <Link to="/login" className="font-semibold text-cyan-400 transition hover:text-cyan-300 hover:underline">Login</Link></p>
  </AuthLayout>;
}
